FROM node:20.11-alpine
WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000

ARG ORG_OPENCONTAINERS_IMAGE_CREATED
ARG ORG_OPENCONTAINERS_IMAGE_REVISION
ARG ORG_OPENCONTAINERS_IMAGE_VERSION

ENV ORG_OPENCONTAINERS_IMAGE_CREATED=${ORG_OPENCONTAINERS_IMAGE_CREATED}
ENV ORG_OPENCONTAINERS_IMAGE_REVISION=${ORG_OPENCONTAINERS_IMAGE_REVISION}
ENV ORG_OPENCONTAINERS_IMAGE_VERSION=${ORG_OPENCONTAINERS_IMAGE_VERSION}

CMD ["node", "-r", "source-map-support/register", "./build/src/index.js"]