import { Database } from "../app"
//import { customAlphabet } from "nanoid"
//const uuid = customAlphabet("1234567890abcdefghjkmnpqrstvwxyz", 20) // crockford-32

///
///
///

declare global {
  interface NumberConstructor {
    parse(input: string | number | undefined | null): number | undefined
  }
}

Object.defineProperty(Number, "parse", {
  value: function (input: string | number | undefined | null): number | undefined {
    if (input === null || input === undefined) return undefined
    if (typeof input === "number") return input
    return isNaN(Number(input)) ? undefined : Number(input)
  },
})

// old ID (table PK) -> new ID (random UUID)
export const _migrator_lookup_table = async (): Promise<{ [key: string]: string }> => {
  return (await _migrator_dual_table())[0]
}

// new ID (random UUID) -> old ID (table PK)
export const _migrator_export_table = async (): Promise<{ [key: string]: string }> => {
  return (await _migrator_dual_table())[1]
}

// BOTH of the above; more performant as well
export const _migrator_dual_table = async (): Promise<[{ [key: string]: string }, { [key: string]: string }]> => {
  const _res = await Database.use("root").baseView("", "", { viewPath: "_local_docs" }, { include_docs: true })
  const output: { [key: string]: string }[] = [{}, {}]
  for (const x of _res.rows) {
    output[0][x.id.replace("_local/", "")] = x.doc.value
    output[1][x.doc.value] = x.id.replace("_local/", "")
  }
  return output as any
}

// TODO: DELETE
function Identifier_pack(components: any[]): string {
  if (components.length === 0) return ""
  return Buffer.from(components.join(":")).toString("base64").replace(/=/g, "~")
}
// TODO: DELETE
export function Activity_pack_id(components: { ctest_id?: number; survey_id?: number; group_id?: number }): string {
  return Identifier_pack(["Activity", components.ctest_id || 0, components.survey_id || 0, components.group_id || 0])
}

export const ActivityIndex: any[] = [
  {
    ActivityIndexID: "1",
    Name: "lamp.survey",
    TableName: "SurveyResult",
    IndexColumnName: "SurveyResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: null,
    Slot1ColumnName: null,
    Slot2Name: null,
    Slot2ColumnName: null,
    Slot3Name: null,
    Slot3ColumnName: null,
    Slot4Name: null,
    Slot4ColumnName: null,
    Slot5Name: null,
    Slot5ColumnName: null,
    TemporalTableName: "SurveyResultDtl",
    TemporalIndexColumnName: "SurveyResultDtlID",
    Temporal1ColumnName: "Question",
    Temporal2ColumnName: "CorrectAnswer",
    Temporal3ColumnName: "ClickRange",
    Temporal4ColumnName: "TimeTaken",
    Temporal5ColumnName: null,
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: null,
  },
  {
    ActivityIndexID: "2",
    Name: "lamp.nback",
    TableName: "CTest_NBackResult",
    IndexColumnName: "NBackResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "score",
    Slot1ColumnName: "Score",
    Slot2Name: "correct_answers",
    Slot2ColumnName: "CorrectAnswers",
    Slot3Name: "wrong_answers",
    Slot3ColumnName: "WrongAnswers",
    Slot4Name: "total_questions",
    Slot4ColumnName: "TotalQuestions",
    Slot5Name: "version",
    Slot5ColumnName: "Version",
    TemporalTableName: null,
    TemporalIndexColumnName: null,
    Temporal1ColumnName: null,
    Temporal2ColumnName: null,
    Temporal3ColumnName: null,
    Temporal4ColumnName: null,
    Temporal5ColumnName: null,
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 1,
  },
  {
    ActivityIndexID: "3",
    Name: "lamp.trails_b",
    TableName: "CTest_TrailsBResult",
    IndexColumnName: "TrailsBResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "rating",
    Slot2ColumnName: "Rating",
    Slot3Name: "score",
    Slot3ColumnName: "Score",
    Slot4Name: "total_attempts",
    Slot4ColumnName: "TotalAttempts",
    Slot5Name: null,
    Slot5ColumnName: null,
    TemporalTableName: "CTest_TrailsBResultDtl",
    TemporalIndexColumnName: "TrailsBResultDtlID",
    Temporal1ColumnName: "Alphabet",
    Temporal2ColumnName: null,
    Temporal3ColumnName: "Status",
    Temporal4ColumnName: "TimeTaken",
    Temporal5ColumnName: "Sequence",
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 2,
  },
  {
    ActivityIndexID: "4",
    Name: "lamp.spatial_span",
    TableName: "CTest_SpatialResult",
    IndexColumnName: "SpatialResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "score",
    Slot2ColumnName: "Score",
    Slot3Name: "correct_answers",
    Slot3ColumnName: "CorrectAnswers",
    Slot4Name: "wrong_answers",
    Slot4ColumnName: "WrongAnswers",
    Slot5Name: "type",
    Slot5ColumnName: "Type",
    TemporalTableName: "CTest_SpatialResultDtl",
    TemporalIndexColumnName: "SpatialResultDtlID",
    Temporal1ColumnName: "GameIndex",
    Temporal2ColumnName: "Sequence",
    Temporal3ColumnName: "Status",
    Temporal4ColumnName: "TimeTaken",
    Temporal5ColumnName: "Level",
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 3,
  },
  {
    ActivityIndexID: "5",
    Name: "lamp.simple_memory",
    TableName: "CTest_SimpleMemoryResult",
    IndexColumnName: "SimpleMemoryResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "score",
    Slot1ColumnName: "Score",
    Slot2Name: "correct_answers",
    Slot2ColumnName: "CorrectAnswers",
    Slot3Name: "wrong_answers",
    Slot3ColumnName: "WrongAnswers",
    Slot4Name: "total_questions",
    Slot4ColumnName: "TotalQuestions",
    Slot5Name: "version",
    Slot5ColumnName: "Version",
    TemporalTableName: null,
    TemporalIndexColumnName: null,
    Temporal1ColumnName: null,
    Temporal2ColumnName: null,
    Temporal3ColumnName: null,
    Temporal4ColumnName: null,
    Temporal5ColumnName: null,
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 5,
  },
  {
    ActivityIndexID: "6",
    Name: "lamp.serial7s",
    TableName: "CTest_Serial7Result",
    IndexColumnName: "Serial7ResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "score",
    Slot2ColumnName: "Score",
    Slot3Name: "total_attempts",
    Slot3ColumnName: "TotalAttempts",
    Slot4Name: "total_questions",
    Slot4ColumnName: "TotalQuestions",
    Slot5Name: "version",
    Slot5ColumnName: "Version",
    TemporalTableName: null,
    TemporalIndexColumnName: null,
    Temporal1ColumnName: null,
    Temporal2ColumnName: null,
    Temporal3ColumnName: null,
    Temporal4ColumnName: null,
    Temporal5ColumnName: null,
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 6,
  },
  {
    ActivityIndexID: "7",
    Name: "lamp.cats_and_dogs",
    TableName: "CTest_CatAndDogResult",
    IndexColumnName: "CatAndDogResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "rating",
    Slot2ColumnName: "Rating",
    Slot3Name: "correct_answers",
    Slot3ColumnName: "CorrectAnswers",
    Slot4Name: "wrong_answers",
    Slot4ColumnName: "WrongAnswers",
    Slot5Name: "total_questions",
    Slot5ColumnName: "TotalQuestions",
    TemporalTableName: null,
    TemporalIndexColumnName: null,
    Temporal1ColumnName: null,
    Temporal2ColumnName: null,
    Temporal3ColumnName: null,
    Temporal4ColumnName: null,
    Temporal5ColumnName: null,
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 7,
  },
  {
    ActivityIndexID: "8",
    Name: "lamp.3d_figure_copy",
    TableName: "CTest_3DFigureResult",
    IndexColumnName: "3DFigureResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "drawn_fig_file_name",
    Slot2ColumnName: "DrawnFigFileName",
    Slot3Name: "game_name",
    Slot3ColumnName: "GameName",
    Slot4Name: null,
    Slot4ColumnName: null,
    Slot5Name: null,
    Slot5ColumnName: null,
    TemporalTableName: null,
    TemporalIndexColumnName: null,
    Temporal1ColumnName: null,
    Temporal2ColumnName: null,
    Temporal3ColumnName: null,
    Temporal4ColumnName: null,
    Temporal5ColumnName: null,
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 8,
  },
  {
    ActivityIndexID: "9",
    Name: "lamp.visual_association",
    TableName: "CTest_VisualAssociationResult",
    IndexColumnName: "VisualAssocResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "score",
    Slot2ColumnName: "Score",
    Slot3Name: "total_attempts",
    Slot3ColumnName: "TotalAttempts",
    Slot4Name: "total_questions",
    Slot4ColumnName: "TotalQuestions",
    Slot5Name: "version",
    Slot5ColumnName: "Version",
    TemporalTableName: null,
    TemporalIndexColumnName: null,
    Temporal1ColumnName: null,
    Temporal2ColumnName: null,
    Temporal3ColumnName: null,
    Temporal4ColumnName: null,
    Temporal5ColumnName: null,
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 9,
  },
  {
    ActivityIndexID: "10",
    Name: "lamp.digit_span",
    TableName: "CTest_DigitSpanResult",
    IndexColumnName: "DigitSpanResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "score",
    Slot2ColumnName: "Score",
    Slot3Name: "correct_answers",
    Slot3ColumnName: "CorrectAnswers",
    Slot4Name: "wrong_answers",
    Slot4ColumnName: "WrongAnswers",
    Slot5Name: "type",
    Slot5ColumnName: "Type",
    TemporalTableName: null,
    TemporalIndexColumnName: null,
    Temporal1ColumnName: null,
    Temporal2ColumnName: null,
    Temporal3ColumnName: null,
    Temporal4ColumnName: null,
    Temporal5ColumnName: null,
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 10,
  },
  {
    ActivityIndexID: "11",
    Name: "lamp.cats_and_dogs_new",
    TableName: "CTest_CatAndDogNewResult",
    IndexColumnName: "CatAndDogNewResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "score",
    Slot2ColumnName: "Score",
    Slot3Name: "correct_answers",
    Slot3ColumnName: "CorrectAnswers",
    Slot4Name: "wrong_answers",
    Slot4ColumnName: "WrongAnswers",
    Slot5Name: null,
    Slot5ColumnName: null,
    TemporalTableName: null,
    TemporalIndexColumnName: null,
    Temporal1ColumnName: null,
    Temporal2ColumnName: null,
    Temporal3ColumnName: null,
    Temporal4ColumnName: null,
    Temporal5ColumnName: null,
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 11,
  },
  {
    ActivityIndexID: "12",
    Name: "lamp.temporal_order",
    TableName: "CTest_TemporalOrderResult",
    IndexColumnName: "TemporalOrderResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "score",
    Slot2ColumnName: "Score",
    Slot3Name: "correct_answers",
    Slot3ColumnName: "CorrectAnswers",
    Slot4Name: "wrong_answers",
    Slot4ColumnName: "WrongAnswers",
    Slot5Name: "version",
    Slot5ColumnName: "Version",
    TemporalTableName: null,
    TemporalIndexColumnName: null,
    Temporal1ColumnName: null,
    Temporal2ColumnName: null,
    Temporal3ColumnName: null,
    Temporal4ColumnName: null,
    Temporal5ColumnName: null,
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 12,
  },
  {
    ActivityIndexID: "13",
    Name: "lamp.nback_new",
    TableName: "CTest_NBackNewResult",
    IndexColumnName: "NBackNewResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "score",
    Slot2ColumnName: "Score",
    Slot3Name: "correct_answers",
    Slot3ColumnName: "CorrectAnswers",
    Slot4Name: "wrong_answers",
    Slot4ColumnName: "WrongAnswers",
    Slot5Name: "total_questions",
    Slot5ColumnName: "TotalQuestions",
    TemporalTableName: null,
    TemporalIndexColumnName: null,
    Temporal1ColumnName: null,
    Temporal2ColumnName: null,
    Temporal3ColumnName: null,
    Temporal4ColumnName: null,
    Temporal5ColumnName: null,
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 14,
  },
  {
    ActivityIndexID: "14",
    Name: "lamp.trails_b_new",
    TableName: "CTest_TrailsBNewResult",
    IndexColumnName: "TrailsBNewResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "rating",
    Slot2ColumnName: "Rating",
    Slot3Name: "score",
    Slot3ColumnName: "Score",
    Slot4Name: "total_attempts",
    Slot4ColumnName: "TotalAttempts",
    Slot5Name: "version",
    Slot5ColumnName: "Version",
    TemporalTableName: "CTest_TrailsBNewResultDtl",
    TemporalIndexColumnName: "TrailsBNewResultDtlID",
    Temporal1ColumnName: "Alphabet",
    Temporal2ColumnName: null,
    Temporal3ColumnName: "Status",
    Temporal4ColumnName: "TimeTaken",
    Temporal5ColumnName: "Sequence",
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 15,
  },
  {
    ActivityIndexID: "15",
    Name: "lamp.trails_b_dot_touch",
    TableName: "CTest_TrailsBDotTouchResult",
    IndexColumnName: "TrailsBDotTouchResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "rating",
    Slot2ColumnName: "Rating",
    Slot3Name: "score",
    Slot3ColumnName: "Score",
    Slot4Name: "total_attempts",
    Slot4ColumnName: "TotalAttempts",
    Slot5Name: null,
    Slot5ColumnName: null,
    TemporalTableName: "CTest_TrailsBDotTouchResultDtl",
    TemporalIndexColumnName: "TrailsBDotTouchResultDtlID",
    Temporal1ColumnName: "Alphabet",
    Temporal2ColumnName: null,
    Temporal3ColumnName: "Status",
    Temporal4ColumnName: "TimeTaken",
    Temporal5ColumnName: "Sequence",
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 16,
  },
  {
    ActivityIndexID: "16",
    Name: "lamp.jewels_a",
    TableName: "CTest_JewelsTrailsAResult",
    IndexColumnName: "JewelsTrailsAResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "score",
    Slot2ColumnName: "Score",
    Slot3Name: "total_attempts",
    Slot3ColumnName: "TotalAttempts",
    Slot4Name: "total_bonus_collected",
    Slot4ColumnName: "TotalBonusCollected",
    Slot5Name: "total_jewels_collected",
    Slot5ColumnName: "TotalJewelsCollected",
    TemporalTableName: "CTest_JewelsTrailsAResultDtl",
    TemporalIndexColumnName: "JewelsTrailsAResultDtlID",
    Temporal1ColumnName: "Alphabet",
    Temporal2ColumnName: null,
    Temporal3ColumnName: "Status",
    Temporal4ColumnName: "TimeTaken",
    Temporal5ColumnName: "Sequence",
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 17,
  },
  {
    ActivityIndexID: "17",
    Name: "lamp.jewels_b",
    TableName: "CTest_JewelsTrailsBResult",
    IndexColumnName: "JewelsTrailsBResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "score",
    Slot2ColumnName: "Score",
    Slot3Name: "total_attempts",
    Slot3ColumnName: "TotalAttempts",
    Slot4Name: "total_bonus_collected",
    Slot4ColumnName: "TotalBonusCollected",
    Slot5Name: "total_jewels_collected",
    Slot5ColumnName: "TotalJewelsCollected",
    TemporalTableName: "CTest_JewelsTrailsBResultDtl",
    TemporalIndexColumnName: "JewelsTrailsBResultDtlID",
    Temporal1ColumnName: "Alphabet",
    Temporal2ColumnName: null,
    Temporal3ColumnName: "Status",
    Temporal4ColumnName: "TimeTaken",
    Temporal5ColumnName: "Sequence",
    SettingsSlots: "",
    SettingsDefaults: null,
    LegacyCTestID: 18,
  },
  {
    ActivityIndexID: "18",
    Name: "lamp.scratch_image",
    TableName: "CTest_ScratchImageResult",
    IndexColumnName: "ScratchImageResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "EndTime",
    Slot1Name: "point",
    Slot1ColumnName: "Point",
    Slot2Name: "scratch_file_name",
    Slot2ColumnName: "DrawnFigFileName",
    Slot3Name: "game_name",
    Slot3ColumnName: "GameName",
    Slot4Name: null,
    Slot4ColumnName: null,
    Slot5Name: null,
    Slot5ColumnName: null,
    TemporalTableName: null,
    TemporalIndexColumnName: null,
    Temporal1ColumnName: null,
    Temporal2ColumnName: null,
    Temporal3ColumnName: null,
    Temporal4ColumnName: null,
    Temporal5ColumnName: null,
    SettingsSlots: null,
    SettingsDefaults: null,
    LegacyCTestID: 19,
  },
  {
    ActivityIndexID: "19",
    Name: "lamp.spin_wheel",
    TableName: "CTest_SpinWheelResult",
    IndexColumnName: "SpinWheelResultID",
    StartTimeColumnName: "StartTime",
    EndTimeColumnName: "GameDate",
    Slot1Name: "collected_stars",
    Slot1ColumnName: "CollectedStars",
    Slot2Name: "day_streak",
    Slot2ColumnName: "DayStreak",
    Slot3Name: "streak_spin",
    Slot3ColumnName: "StrakSpin",
    Slot4Name: null,
    Slot4ColumnName: null,
    Slot5Name: null,
    Slot5ColumnName: null,
    TemporalTableName: null,
    TemporalIndexColumnName: null,
    Temporal1ColumnName: null,
    Temporal2ColumnName: null,
    Temporal3ColumnName: null,
    Temporal4ColumnName: null,
    Temporal5ColumnName: null,
    SettingsSlots: null,
    SettingsDefaults: null,
    LegacyCTestID: 20,
  },
]
